# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 20:11
from __future__ import unicode_literals

import alerts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0031_hwinj_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', alerts.models.PhoneNumberField(blank=True, max_length=255, validators=[alerts.models.validate_phone])),
                ('call_phone', models.BooleanField(default=False)),
                ('text_phone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerType', models.CharField(blank=True, choices=[(b'create', b'create'), (b'change', b'change'), (b'label', b'label')], max_length=20)),
                ('farThresh', models.FloatField(blank=True, null=True)),
                ('label_query', models.CharField(blank=True, max_length=100)),
                ('contacts', models.ManyToManyField(to='alerts.Contact')),
                ('labels', models.ManyToManyField(blank=True, to='events.Label')),
                ('pipelines', models.ManyToManyField(blank=True, to='events.Pipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
