# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='call_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_method',
            field=models.CharField(blank=True, choices=[(b'C', b'Call'), (b'T', b'Text'), (b'B', b'Call and text')], default=None, max_length=1, null=True),
        ),
    ]
