# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 16:57
from __future__ import unicode_literals

import alerts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20190121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=alerts.fields.PhoneNumberField(blank=True, max_length=255, null=True),
        ),
    ]
