# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 19:57
# This was auto-generated after moving to Python 3, with no changes to the
# actual models. See the commit message for more details.
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_add_created_updated_time_fields_to_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_method',
            field=models.CharField(blank=True, choices=[('C', 'Call'), ('T', 'Text'), ('B', 'Call and text')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('E', 'Event'), ('S', 'Superevent')], default='S', max_length=1),
        ),
    ]
