# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20190121_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
