# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20190121_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verification_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='verification_requested',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
