# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20190123_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='verification_expires',
            new_name='verification_expiration',
        ),
    ]
