# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_hwinj_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0008_auto_20190123_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_threshold', models.FloatField(blank=True, null=True)),
                ('label_query', models.CharField(blank=True, max_length=100, null=True)),
                ('ns_candidate', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(to='alerts.Contact')),
                ('groups', models.ManyToManyField(to='events.Group')),
                ('labels', models.ManyToManyField(to='events.Label')),
                ('pipelines', models.ManyToManyField(to='events.Pipeline')),
                ('searches', models.ManyToManyField(to='events.Search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupereventNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_threshold', models.FloatField(blank=True, null=True)),
                ('label_query', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.ManyToManyField(to='alerts.Contact')),
                ('labels', models.ManyToManyField(to='events.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='pipelines',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
