# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20190131_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='supereventnotification',
            name='ns_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
