# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_supereventnotification_ns_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotification',
            name='groups',
            field=models.ManyToManyField(blank=True, to='events.Group'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='labels',
            field=models.ManyToManyField(blank=True, to='events.Label'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='pipelines',
            field=models.ManyToManyField(blank=True, to='events.Pipeline'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='searches',
            field=models.ManyToManyField(blank=True, to='events.Search'),
        ),
        migrations.AlterField(
            model_name='supereventnotification',
            name='labels',
            field=models.ManyToManyField(blank=True, to='events.Label'),
        ),
    ]
