# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_auto_20190201_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
