# Generated by Django 3.2.20 on 2024-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwtc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwtc_catalog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gwtc_superevent',
            name='far',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gwtc_superevent',
            name='pastro',
            field=models.JSONField(null=True),
        ),
        migrations.AddIndex(
            model_name='gwtc_superevent',
            index=models.Index(fields=['far'], name='gwtc_gwtc_s_far_b638f1_idx'),
        ),
    ]
