# Generated by Django 4.2.21 on 2025-07-21 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwtc', '0002_gwtc_far_pastro_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwtc_catalog',
            name='number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, dots, underscores, and hyphens are allowed.', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
