---
image: docker:latest

variables:
  APT_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/apt"
  DOCKER_DRIVER: overlay
  DOCKER_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_LATEST: $CI_REGISTRY_IMAGE:latest
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

stages:
  - test
  - branch
  - latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

include:
  # Container scanning
  - component: $CI_SERVER_FQDN/computing/gitlab/components/container-scanning/container-scanning@~latest
    inputs:
      job_name: branch_scan

  # Software scanning
  - component: $CI_SERVER_FQDN/computing/gitlab/components/sast/sast@~latest
    inputs:
      run_advanced_sast: true
  - component: $CI_SERVER_FQDN/computing/gitlab/components/secret-detection/secret-detection@~latest
  - component: $CI_SERVER_FQDN/computing/gitlab/components/python/dependency-scanning@~latest

# -- software scanning
# overwrite some settings for the scanning jobs

dependency_scanning:
  stage: test
  needs: []
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    # install some underlying utilities using `apt` so that the dependency
    # scanner can use pip to install everything else
    - apt-get update -yqq
    - apt-get install -yqq
        libkrb5-dev
        libldap-dev
        libsasl2-dev

.sast-analyzer:
  stage: test
  needs: []
  before_script: []

secret_detection:
  stage: test
  needs: []
  before_script: []

# -- testing

.test: &test
  image: debian:trixie
  services:
    - postgres:15.6
    - memcached
  variables:
    AWS_SES_ACCESS_KEY_ID: "fake_aws_id"
    AWS_SES_SECRET_ACCESS_KEY: "fake_aws_key"
    DJANGO_ALERT_EMAIL_FROM: "fake_email"
    DJANGO_DB_HOST: "postgres"
    DJANGO_DB_PORT: "5432"
    DJANGO_DB_NAME: "fake_name"
    DJANGO_DB_USER: "runner"
    DJANGO_DB_PASSWORD: ""
    DJANGO_PRIMARY_FQDN: "fake_fqdn"
    DJANGO_SECRET_KEY: "fake_key"
    DJANGO_SETTINGS_MODULE: "config.settings.container.dev"
    DJANGO_TWILIO_ACCOUNT_SID: "fake_sid"
    DJANGO_TWILIO_AUTH_TOKEN: "fake_token"
    DJANGO_DOCKER_MEMCACHED_ADDR: "memcached:11211"
    EGAD_URL: "fake_url"
    EGAD_API_KEY: "fake_key"
    ENABLE_LVALERT_OVERSEER: "false"
    ENABLE_IGWN_OVERSEER: "false"
    LVALERT_OVERSEER_PORT: "2"
    LVALERT_SERVER: "fake_server"
    LVALERT_USER: "fake_user"
    LVALERT_PASSWORD: "fake_password"
    ENABLE_IGWN_OVERSEER: "false"
    IGWN_ALERT_OVERSEER_PORT: "2"
    IGWN_ALERT_SERVER: "fake_server"
    IGWN_ALERT_USER: "fake_user"
    IGWN_ALERT_PASSWORD: "fake_password"
    POSTGRES_DB: "${DJANGO_DB_NAME}"
    POSTGRES_USER: "${DJANGO_DB_USER}"
    POSTGRES_PASSWORD: "${DJANGO_DB_PASSWORD}"
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    # create apt cache directory
    - mkdir -pv ${APT_CACHE_DIR}
    # set python version
    - PYTHON_VERSION="${CI_JOB_NAME##*:}"
    - PYTHON_MAJOR="${PYTHON_VERSION:0:1}"
    - PYTHON="python3"
    # build apt cache:
    - apt-get -yqq update
    # install build requirements
    - apt-get -y install gnupg lsb-release curl
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
    - apt-get -yqq update
    - apt-get -o dir::cache::archives="${APT_CACHE_DIR}" install -yqq
          git
          gnupg
          libldap2-dev
          libsasl2-dev
          libssl-dev
          libxml2-dev
          krb5-user
          libkrb5-dev
          libsasl2-modules-gssapi-mit
          swig
          pkg-config 
          libpng-dev 
          libfreetype6-dev 
          libxslt-dev
          ${PYTHON}-pip
          postgresql-15
          postgresql-client-15
          libpq-dev
    # install everything else from pip
    - ${PYTHON} -m pip install -r requirements.txt --break-system-packages
    # create logs path required for tests
    - mkdir -pv ../logs/
    # list packages
    - ${PYTHON} -m pip list installed
  script:
    - PYTHONPATH=${PYTHONPATH}:${PWD}/gracedb ${PYTHON} -m pytest --cov-report term-missing --cov ./gracedb --junitxml=${CI_PROJECT_DIR}/junit.xml
  after_script:
    - rm -fvr ${PIP_CACHE_DIR}/log
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  artifacts:
    reports:
      junit: junit.xml
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .cache/pip
      - .cache/apt
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  tags:
      - executor-docker

test:3.13:
  <<: *test

# -- docker

branch_image:
  stage: branch
  script:
    - docker build --pull -t $DOCKER_BRANCH .
    - docker push $DOCKER_BRANCH
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  tags:
      - executor-docker

branch_scan:
  stage: branch
  needs: [branch_image]
  # default rules spawn a merge request pipeline, we don't want that
  rules:
    - if: $CI_COMMIT_BRANCH
  variables:
    GIT_STRATEGY: fetch
    # image to scan
    CS_IMAGE: "$DOCKER_BRANCH"
    # image to compare to
    CS_DEFAULT_BRANCH_IMAGE: "$CI_REGISTRY/computing/gitlab/server:latest"
    # path to Dockerfile for remediation
    CS_DOCKERFILE_PATH: "Dockerfile"
  before_script: []

latest_image:
  stage: latest
  dependencies:
    - branch_image
  script:
    - docker pull $DOCKER_BRANCH
    - docker tag $DOCKER_BRANCH $DOCKER_LATEST
    - docker push $DOCKER_LATEST
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  tags:
      - executor-docker
