from django.shortcuts import get_object_or_404

from .models import Superevent, Log, Labelling
from events.models import Event, EventLog, Tag
from events.permission_utils import assign_default_perms
from core.vfile import VersionedFile

import os

import logging
logger = logging.getLogger(__name__)

# NOTE: everything in here assumes that permissions have already been checked
# and handled properly

# TODO:
# Add decorator to check access permissions (??) not sure if we should do it here or in the viewset itself
def create_superevent(submitter, t_start, t_0, t_end, preferred_event,
    events=[], labels=[], add_log_message=True, issue_alert=True):
    """
    Utility method for creating superevents.

    Arguments:
        submitter: User object (required)
        t_start, t_0, t_end: floats (required)
        preferred_event: Event object (required)
        events: list or QuerySet of Event objects
        labels: list of QuerySet of Label objects

    Usage:
        create_superevent(
            UserModel.objects.get(username='albert.einstein@ligo.org'),
            t_start=1, t_0=2, t_end=3, preferred_event=
            Event.objects.get(id='123400')
        )
    """

    # Create superevent
    s = Superevent.objects.create(submitter=submitter, t_start=t_start,
        t_0=t_0, t_end=t_end, preferred_event=preferred_event)

    # Write a log message for preferred event
    new_msg = "Set as preferred event for superevent: {superevent_id}" \
        .format(superevent_id=s.superevent_id)
    new_log = create_log(submitter, new_msg, preferred_event,
        issue_alert=True, autogenerated=False)

    # Add events to superevent
    # Superevent log message and alerts are taken care of elsewhere, but we
    # want to record logs and send alerts for the individual events
    for event in events:
        add_event_to_superevent(s, event, submitter, add_superevent_log=False,
            add_event_log=True, issue_superevent_alert=False,
            issue_event_alert=True)

    # Create a log message to record initial superevent parameters
    # TODO: alert issued for log or not? probably not
    creation_comment = ("Superevent created with t_start={t_start}, t_0={t_0},"
        " t_end={t_end}, preferred_event={preferred_event}").format(
        t_start=t_start, t_0=t_0, t_end=t_end, preferred_event=preferred_event)

    if events:
        creation_comment += ", events={events}".format(events=", ".join(
            [ev.graceid() for ev in events]))

    # This is autogenerated, but people probably don't want to hide it
    # in the web interface
    superevent_creation_log = create_log(submitter, creation_comment, s,
        issue_alert=False, autogenerated=False)

    # Add labels
    send_label_alert = False
    if labels:
        send_label_alert = True
        for label in labels:
            l = add_label_to_superevent(s, label, submitter,
                add_log_message=True, issue_alert=issue_alert)

    # Create default GroupObjectPermissions - LVC group and executives group
    # can view/change superevents
    assign_default_perms(s)

    # Look at event creation functions to see if there is anything else we should add here.
    # CREATE DIRECTORY
    os.makedirs(s.datadir)

    # TODO: Send "new" alert about superevent creation
    if issue_alert:
        pass

    return s


def update_superevent(superevent, updater, issue_alert=True, **kwargs):
    """
    kwargs which are used as superevent parameters:
        t_start, t_0, t_end, preferred_event
    """

    # Extract "updatable" superevent params from kwargs
    param_names = ['t_start', 't_0', 't_end', 'preferred_event']
    new_params = {k: v for k,v in kwargs.iteritems() if k in param_names}

    # Get old parameters
    old_params = {k: getattr(superevent, k) for k in new_params.keys()}

    # Update superevent object
    for k,v in new_params.iteritems():
        setattr(superevent, k, v)
    superevent.save()

    # Write a log message
    # 'if' statement to handle put requests which don't change entire object
    updates = ["{name}: {old} -> {new}".format(name=k, old=old_params[k],
        new=new_params[k]) for k in new_params.keys()
        if old_params[k] != new_params[k]]
    update_comment = "Updated superevent parameters: {0}".format(
        ", ".join(updates))
    update_log = create_log(updater, update_comment, superevent,
        issue_alert=False)

    # Write event log messages if preferred event changed
    if new_params.has_key('preferred_event') and \
        (old_params['preferred_event'] != new_params['preferred_event']):
        # Old preferred event
        old_msg = ("Removed as preferred event for superevent: "
            "{superevent_id}").format(superevent_id=superevent.superevent_id)
        old_log = create_log(updater, old_msg, old_params['preferred_event'],
            issue_alert=True)

        # New preferred event
        new_msg = "Set as preferred event for superevent: {superevent_id}" \
            .format(superevent_id=superevent.superevent_id)
        new_log = create_log(updater, new_msg, new_params['preferred_event'],
            issue_alert=True)

    # TODO: issue alert here? or for log message?
    if issue_alert:
        pass

    return superevent


def create_log(issuer, comment, event_or_superevent, filename="",
    data_file=None, tags=[], issue_alert=False, autogenerated=False):
    """
    Assume data have already been validated by a form or serializer.
    tags should be a list of Tag objects (??)
    """

    # Initial dictionary for log creation
    log_dict = {
        'issuer': issuer,
        'comment': comment,
        'filename': filename,
    }
    if isinstance(event_or_superevent, Superevent):
        log_dict['superevent'] = event_or_superevent
        LogModel = Log
    elif isinstance(event_or_superevent, Event):
        log_dict['event'] = event_or_superevent
        LogModel = EventLog
    else:
        # TODO: raise error
        logger.error(type(event_or_superevent))
        pass

    # Create log object
    log = LogModel.objects.create(**log_dict)

    # Create data file
    if data_file:
        filepath = os.path.join(event_or_superevent.datadir, filename)
        fdest = VersionedFile(filepath, 'w')
        for chunk in data_file.chunks():
            fdest.write(chunk)
        fdest.close()

        # Update file_version
        log.file_version = fdest.version
        log.save()

    # TODO: do we issue alert for "auto-generated" log messages?
    #       or just for the original log message? Dig into the old
    #       API to find out
    for t in tags:
        add_tag_to_log(log, t, issuer, issue_alert=False)

    # TODO:
    # Issue an alert for log
    if issue_alert:
        print('issue alert')

    # TODO:
    # If user is external, add LV-EM tagname to this log message

    return log 


def get_log_parent(log):
    # Determine if this is an event or superevent log
    if isinstance(log, Log):
        return log.superevent
    elif isinstance(log, EventLog):
        return log.event
    else:
        # TODO: raise exception
        pass


def add_tag_to_log(log, tag, user, add_log_message=True, issue_alert=True):
    # Add tag to log
    log.tags.add(tag)

    # Create log message to record tag addition?
    if add_log_message:
        comment = 'Tagged message {N}: {tag_name}'.format(N=log.N,
            tag_name=tag.name)
        event_or_superevent = get_log_parent(log)
        log_for_tag_addition = create_log(user, comment, event_or_superevent,
            issue_alert=issue_alert, autogenerated=True)


def remove_tag_from_log(log, tag, user, add_log_message=True,
    issue_alert=True):

    # Remove tag from log
    log.tags.remove(tag)

    # Create log message to record tag removal?
    if add_log_message:
        comment = 'Removed tag {tag_name} from message {N}'.format(
            N=log.N, tag_name=tag.name),
        event_or_superevent = get_log_parent(log)
        log_for_tag_removal = create_log(user, comment, event_or_superevent,
            issue_alert=issue_alert, autogenerated=True)


def add_event_to_superevent(superevent, event, user, add_event_log=True,
    add_superevent_log=True, issue_event_alert=True,
    issue_superevent_alert=True):

    # Add event to superevent
    superevent.events.add(event)

    # Create superevent log message to record event addtion?
    if add_superevent_log:
        # Record event addition in superevent logs
        superevent_comment = 'Added event: {graceid}'.format(
            graceid=event.graceid())
        superevent_log_for_event_addition = create_log(user,
            superevent_comment, superevent, issue_alert=issue_superevent_alert,
            autogenerated=True)

    # Create event log message to record addition to superevent?
    if add_event_log:
        # Record addition to superevent in event logs
        event_comment = 'Added to superevent: {superevent_id}'.format(
            superevent_id=superevent.superevent_id)
        event_log_for_addition_to_superevent = create_log(user, event_comment,
            event, issue_alert=issue_event_alert, autogenerated=True)

    # TODO: whether this is inside the add_log_message block depends on our
    #       for the below todo.
    if issue_superevent_alert:
        # alerts to superevent channel
        pass

    if issue_event_alert:
        # alerts to event channels
        pass

# TODO: is it enough to just issue alerts about the new log message?
#       or do we need to issue one specifically with the event being added?
#       Might need to serialize the event or superevent in some fashion since
#       we would need to issue the alert from here instead of in create_log.
#       NOTE: same of course needs to be considered for removing events
#             from a superevent


def remove_event_from_superevent(superevent, event, user, add_event_log=True,
    add_superevent_log=True, issue_event_alert=True,
    issue_superevent_alert=True):
    """
    This function should be within a try-except block to catch exceptions and
    convert them to the appropriate response.
    """
    # Throw error if this is the preferred event
    if event == superevent.preferred_event:
        raise Superevent.PreferredEventRemovalError("Can't remove a "
            "superevent's preferred event without setting a new one.")

    # Remove event from superevent
    superevent.events.remove(event)

    # Create superevent log message to record event removal?
    if add_superevent_log:
        # Record event removal in superevent logs
        superevent_comment = 'Removed event: {graceid}'.format(
            graceid=event.graceid())
        superevent_log_for_event_removal = create_log(user, superevent_comment,
            superevent, issue_alert=issue_superevent_alert, autogenerated=True)

    # Create event log message to record removal from superevent?
    if add_event_log:
        event_comment ='Removed from superevent: {superevent_id}'.format(
            superevent_id=superevent.superevent_id),
        event_log_for_removal_from_superevent = create_log(user, event_comment,
            event, issue_alert=issue_event_alert, autogenerated=True)

    # TODO: whether this is inside the add_log_message block depends on our
    #       for the above todo.
    if issue_superevent_alert:
        # alerts to superevent channel
        pass

    if issue_event_alert:
        # alerts to event channels
        pass

def add_label_to_superevent(superevent, label, user, add_log_message=True,
    issue_alert=True):

    # Create Labelling object
    labelling = Labelling.objects.create(label=label, creator=user,
        superevent=superevent)

    if add_log_message:
        # Record label addition in superevent logs
        comment = 'Added label: {label_name}'.format(label_name=label.name)
        log_for_label_addition = create_log(user, comment, superevent,
            issue_alert=issue_alert, autogenerated=True)

    # TODO: send label alert to superevent channel
    if issue_alert:
        pass

    return labelling


def remove_label_from_superevent(labelling, user, add_log_message=True,
    issue_alert=True):

    # Delete Labelling object
    label_name = labelling.label.name
    labelling.delete()

    if add_log_message:
        # Record label addition in superevent logs
        comment = 'Removed label: {label_name}'.format(label_name=label_name)
        log_for_label_removal = create_log(user, comment, labelling.superevent,
            issue_alert=issue_alert, autogenerated=True)

    # TODO: send label alert (or update?) to superevent channel
    #       if we do this, we probably don't send one for log creation, right?
    #       (need to check on this)
    if issue_alert:
        pass


def get_or_create_tag(tag_name, display_name=None):

    tag, created = Tag.objects.get_or_create(name=tag_name)
    if created and display_name is not None:
        tag.displayName = display_name
        tag.save()

    return tag


def get_or_create_tags(tag_name_list, display_name_list=[]):

    # TODO: make this a useful error
    if display_name_list and (len(display_name_list) != len(tag_name_list)):
        raise ValueError('')

    tag_list = []
    for i, tag_name in enumerate(tag_name_list):
        display_name = None
        if display_name_list:
            display_name = display_name_list[i]
        tag = get_or_create_tag(tag_name, display_name)
        tag_list.append(tag)

    return tag_list


# TODO: add permissions checking?
# TODO: move this somewhere else?
def get_superevent_by_date_id_or_404(request, superevent_id):

    filter_kwargs = Superevent.get_filter_kwargs_for_date_id_lookup(
        superevent_id)

    # TODO: filter queryset for user here
    queryset = Superevent.objects.all()

    return get_object_or_404(queryset, **filter_kwargs)


def confirm_superevent_as_gw(superevent, user):

    # Update superevent (mark as a GW, construct new ID, etc.)
    superevent.confirm_as_gw()

    # Create log message
    message = "Confirmed as a gravitational wave."
    gw_log = create_log(user, message, superevent, issue_alert=True,
        autogenerated=False)

    # TODO: add label?

    # TODO:
    # issue alert
