# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_DESGW_to_EMGroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleinspiral',
            name='channel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
