# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 18:23
#
# Adds a new field to the EventLog model which corresponds to tags.
# First step in migrating the many-to-many relationship between
# logs and tags off of the tags model so that it's easier to reuse.


from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_increase_singleinspiral_channel_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='tags',
            field=models.ManyToManyField(to='events.Tag'),
        ),
    ]
