# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 18:28
#
# Delete the old 'through' table between logs and tags

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_migrate_tag_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='eventlogs',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='tags',
            field=models.ManyToManyField(related_name='eventlogs', to='events.Tag'),
        ),
    ]
