# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rename_pipelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emfootprint',
            name='N',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='emobservation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_emobservation_set', to='events.EMGroup'),
        ),
        migrations.AlterField(
            model_name='emobservation',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_emobservation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='N',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='file_version',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='filename',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='tags',
            field=models.ManyToManyField(related_name='event_logs', to='events.Tag'),
        ),
        migrations.AlterField(
            model_name='labelling',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_labelling_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_signoff_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='displayName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='N',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='file_version',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='filename',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_voevent_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='ivorn',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
