# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0001_initial'),
        ('events', '0018_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='superevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='superevents.Superevent'),
        ),
    ]
