# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_emobservation_N_not_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_tag_name', message=b'Tag names can only include [0-9a-zA-z_-]', regex=b'^[0-9a-zA-Z_\\-]*$')]),
        ),
    ]
