# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_restrict_tag_name_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emobservation',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emobservation',
            name='decWidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emobservation',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emobservation',
            name='raWidth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
