# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_explicitly_create_access_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleinspiral',
            name='channel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
