# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_increase_channel_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
