# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_create_bbh_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminspiralevent',
            name='destination_channel',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='source_channel',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
    ]
