# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 20:04
from __future__ import unicode_literals

from django.db import migrations

# Creates initial search instances

# Search names and descriptions
SEARCH = {
    'name': 'SubGRB',
    'description': 'Sub-threshold GRB events',
}

def add_search(apps, schema_editor):
    Search = apps.get_model('events', 'Search')

    # Create search
    Search.objects.create(**SEARCH)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_pipelinelog_and_pipeline_enabled'),
    ]

    operations = [
        migrations.RunPython(add_search, migrations.RunPython.noop),
    ]
