# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_populate_voevent_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approvedEvent',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approver',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
