# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_delete_approval_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[(b'E', b'external'), (b'O', b'other'), (b'SO', b'non-production search'), (b'SP', b'production search')], default='O', max_length=2),
            preserve_default=False,
        ),
    ]
