# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 19:57
# This was auto-generated after moving to Python 3, with no changes to the
# actual models. See the commit message for more details.
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_specify_pipeline_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coincinspiralevent',
            name='ifos',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='embbeventlog',
            name='eel_status',
            field=models.CharField(choices=[('FO', 'FOOTPRINT'), ('SO', 'SOURCE'), ('CO', 'COMMENT'), ('CI', 'CIRCULAR')], max_length=2),
        ),
        migrations.AlterField(
            model_name='embbeventlog',
            name='obs_status',
            field=models.CharField(choices=[('NA', 'NOT APPLICABLE'), ('OB', 'OBSERVATION'), ('TE', 'TEST'), ('PR', 'PREDICTION')], max_length=2),
        ),
        migrations.AlterField(
            model_name='embbeventlog',
            name='waveband',
            field=models.CharField(choices=[('em.gamma', 'Gamma rays part of the spectrum'), ('em.gamma.soft', 'Soft gamma ray (120 - 500 keV)'), ('em.gamma.hard', 'Hard gamma ray (>500 keV)'), ('em.X-ray', 'X-ray part of the spectrum'), ('em.X-ray.soft', 'Soft X-ray (0.12 - 2 keV)'), ('em.X-ray.medium', 'Medium X-ray (2 - 12 keV)'), ('em.X-ray.hard', 'Hard X-ray (12 - 120 keV)'), ('em.UV', 'Ultraviolet part of the spectrum'), ('em.UV.10-50nm', 'Ultraviolet between 10 and 50 nm'), ('em.UV.50-100nm', 'Ultraviolet between 50 and 100 nm'), ('em.UV.100-200nm', 'Ultraviolet between 100 and 200 nm'), ('em.UV.200-300nm', 'Ultraviolet between 200 and 300 nm'), ('em.UV.FUV', 'Far-Infrared, 30-100 microns'), ('em.opt', 'Optical part of the spectrum'), ('em.opt.U', 'Optical band between 300 and 400 nm'), ('em.opt.B', 'Optical band between 400 and 500 nm'), ('em.opt.V', 'Optical band between 500 and 600 nm'), ('em.opt.R', 'Optical band between 600 and 750 nm'), ('em.opt.I', 'Optical band between 750 and 1000 nm'), ('em.IR', 'Infrared part of the spectrum'), ('em.IR.NIR', 'Near-Infrared, 1-5 microns'), ('em.IR.J', 'Infrared between 1.0 and 1.5 micron'), ('em.IR.H', 'Infrared between 1.5 and 2 micron'), ('em.IR.K', 'Infrared between 2 and 3 micron'), ('em.IR.MIR', 'Medium-Infrared, 5-30 microns'), ('em.IR.3-4um', 'Infrared between 3 and 4 micron'), ('em.IR.4-8um', 'Infrared between 4 and 8 micron'), ('em.IR.8-15um', 'Infrared between 8 and 15 micron'), ('em.IR.15-30um', 'Infrared between 15 and 30 micron'), ('em.IR.30-60um', 'Infrared between 30 and 60 micron'), ('em.IR.60-100um', 'Infrared between 60 and 100 micron'), ('em.IR.FIR', 'Far-Infrared, 30-100 microns'), ('em.mm', 'Millimetric part of the spectrum'), ('em.mm.1500-3000GHz', 'Millimetric between 1500 and 3000 GHz'), ('em.mm.750-1500GHz', 'Millimetric between 750 and 1500 GHz'), ('em.mm.400-750GHz', 'Millimetric between 400 and 750 GHz'), ('em.mm.200-400GHz', 'Millimetric between 200 and 400 GHz'), ('em.mm.100-200GHz', 'Millimetric between 100 and 200 GHz'), ('em.mm.50-100GHz', 'Millimetric between 50 and 100 GHz'), ('em.mm.30-50GHz', 'Millimetric between 30 and 50 GHz'), ('em.radio', 'Radio part of the spectrum'), ('em.radio.12-30GHz', 'Radio between 12 and 30 GHz'), ('em.radio.6-12GHz', 'Radio between 6 and 12 GHz'), ('em.radio.3-6GHz', 'Radio between 3 and 6 GHz'), ('em.radio.1500-3000MHz', 'Radio between 1500 and 3000 MHz'), ('em.radio.750-1500MHz', 'Radio between 750 and 1500 MHz'), ('em.radio.400-750MHz', 'Radio between 400 and 750 MHz'), ('em.radio.200-400MHz', 'Radio between 200 and 400 MHz'), ('em.radio.100-200MHz', 'Radio between 100 and 200 MHz'), ('em.radio.20-100MHz', 'Radio between 20 and 100 MHz')], max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='instruments',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='label',
            name='defaultColor',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='multiburstevent',
            name='ifos',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='multiburstevent',
            name='single_ifo_times',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('E', 'external'), ('O', 'other'), ('SO', 'non-production search'), ('SP', 'production search')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pipelinelog',
            name='action',
            field=models.CharField(choices=[('D', 'disable'), ('E', 'enable')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='instrument',
            field=models.CharField(blank=True, choices=[('H1', 'LHO'), ('L1', 'LLO'), ('V1', 'Virgo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='signoff_type',
            field=models.CharField(choices=[('OP', 'operator'), ('ADV', 'advocate')], max_length=3),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='status',
            field=models.CharField(choices=[('OK', 'OKAY'), ('NO', 'NOT OKAY')], max_length=2),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='destination_channel',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='numrel_data',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='source_channel',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='taper',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='waveform',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag_name', message='Tag names can only include [0-9a-zA-z_-]', regex='^[0-9a-zA-Z_\\-]*$')]),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='ivorn',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='voevent_type',
            field=models.CharField(choices=[('PR', 'preliminary'), ('IN', 'initial'), ('UP', 'update'), ('RE', 'retraction')], max_length=2),
        ),
    ]
