# Generated by Django 2.2 on 2020-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_specify_integralagile_pipeline_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('manage_pipeline', 'Can enable or disable pipeline'),)},
        ),
        migrations.AlterField(
            model_name='voevent',
            name='coinc_comment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='hardware_inj',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='internal',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='open_alert',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='raven_coinc',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
