# Generated by Django 2.2.10 on 2020-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_add_subgrbtargeted_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voevent',
            name='voevent_type',
            field=models.CharField(choices=[('PR', 'preliminary'), ('IN', 'initial'), ('UP', 'update'), ('RE', 'retraction'), ('EW', 'earlywarning')], max_length=2),
        ),
    ]
