# Generated by Django 3.2.9 on 2022-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_add_MBTA_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='graceid',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
