# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 20:07:23
from __future__ import unicode_literals

from django.db import migrations

# List of label names, default colors, and descriptions
LABELS = [
    {
	'name': 'PRELIM',
	'defaultColor': 'black',
	'description': 'Preliminary PE results ready.',
    },
    {
	'name': 'FINAL',
	'defaultColor': 'green',
	'description': 'Final PE results ready.',
    },
    {
	'name': 'NONE',
	'defaultColor': 'red',
	'description': 'No PE results ready.',
    },
    {
        'name': 'CHUNK_1',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_2',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_3',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_4',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_5',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_6',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_7',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_8',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_9',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_10',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_11',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_12',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_13',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_14',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_15',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_16',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_17',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_18',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_19',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_20',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_21',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_22',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_23',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_24',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_25',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_26',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_27',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_28',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_29',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_30',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_31',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_32',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_33',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_34',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_35',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_36',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_37',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_38',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_39',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_40',
        'defaultColor': 'black',
        'description': 'This is the chunk for this event.',
    },
    {
        'name': 'CHUNK_UNKNOWN',
        'defaultColor': 'black',
        'description': 'Error assigning chunk to this event.',
    },
]

def add_labels(apps, schema_editor):
    Label = apps.get_model('events', 'Label')

    # Create labels
    for label_dict in LABELS:
        l, created = Label.objects.get_or_create(name=label_dict['name'])
        l.defaultColor = label_dict['defaultColor']
        l.description = label_dict['description']
        l.save()


def remove_labels(apps, schema_editor):
    Label = apps.get_model('events', 'Label')

    # Delete labels
    for label_dict in LABELS:
        try:
            l = Label.objects.get(name=label_dict['name'])
        except Label.DoesNotExist:
            print('Label {0} not found to be deleted, skipping.' \
                .format(label_dict['name']))
            break
        l.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_add_MBTA_pipeline'),
    ]

    operations = [
        migrations.RunPython(add_labels, remove_labels),
    ]
