# Generated by Django 3.2.9 on 2022-03-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_add_MLy_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLyBurstEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('ifos', models.CharField(default='', max_length=20)),
                ('score_coinc', models.FloatField(null=True)),
                ('score_coher', models.FloatField(null=True)),
                ('score_comb', models.FloatField(null=True)),
                ('central_freq', models.FloatField(null=True)),
                ('bandwidth', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('central_time', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('events.event',),
        ),
    ]
