# Generated by Django 2.2.10 on 2020-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_add_more_catalog_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gw_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
