# Generated by Django 3.2.9 on 2022-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_mlyburstevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reporting_latency',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=16, null=True),
        ),
    ]
