# Generated by Django 3.2.9 on 2022-08-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_add_dqr_request_label'),
        ('events', '0057_event_pipeline_preferred'),
    ]

    operations = [
    ]
