# Generated by Django 3.2.9 on 2022-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_voevent_prob_has_mass_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='siminspiralevent',
            name='amplitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='siminspiralevent',
            name='freq',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='siminspiralevent',
            name='phi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='siminspiralevent',
            name='tau',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='numrel_data',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='taper',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siminspiralevent',
            name='waveform',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
