# Generated by Django 3.2.9 on 2023-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_auto_20221202_1955'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['graceid'], name='events_even_graceid_6a15d5_idx'),
        ),
    ]
