# Generated by Django 3.2.9 on 2023-01-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_event_events_even_graceid_6a15d5_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['filename'], name='events_even_filenam_2178d5_idx'),
        ),
    ]
