# Generated by Django 3.2.9 on 2023-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_eventlog_events_even_filenam_2178d5_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['name'], name='events_labe_name_bdb62a_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['name'], name='events_pipe_name_8d66d2_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['name'], name='events_sear_name_b41897_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='events_tag_name_194bf7_idx'),
        ),
    ]
