# Generated by Django 3.2.9 on 2023-01-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_auto_20230115_1459'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['ifos'], name='events_coin_ifos_09d166_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['mass'], name='events_coin_mass_e55dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['mchirp'], name='events_coin_mchirp_8d2ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['minimum_duration'], name='events_coin_minimum_06261b_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['snr'], name='events_coin_snr_32f045_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['false_alarm_rate'], name='events_coin_false_a_d09060_idx'),
        ),
        migrations.AddIndex(
            model_name='coincinspiralevent',
            index=models.Index(fields=['combined_far'], name='events_coin_combine_d87859_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['gpstime'], name='events_even_gpstime_963dab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['instruments'], name='events_even_instrum_ae71e4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['far'], name='events_even_far_8d2c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['likelihood'], name='events_even_likelih_3089e1_idx'),
        ),
        migrations.AddIndex(
            model_name='grbevent',
            index=models.Index(fields=['trigger_id'], name='events_grbe_trigger_f9adf1_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['ifos'], name='events_mlyb_ifos_7b416e_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['score_coinc'], name='events_mlyb_score_c_afaaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['score_coher'], name='events_mlyb_score_c_2194eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['score_comb'], name='events_mlyb_score_c_5576d7_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['central_freq'], name='events_mlyb_central_1dcdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['bandwidth'], name='events_mlyb_bandwid_c6e0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['duration'], name='events_mlyb_duratio_a7e3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['central_time'], name='events_mlyb_central_58faef_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['ifos'], name='events_mult_ifos_9f76aa_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['duration'], name='events_mult_duratio_56fd97_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['central_freq'], name='events_mult_central_ea79da_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['snr'], name='events_mult_snr_687151_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['single_ifo_times'], name='events_mult_single__bcd9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['ifo'], name='events_sing_ifo_d12e96_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['search'], name='events_sing_search_a775b4_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['channel'], name='events_sing_channel_6d8257_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['mass1'], name='events_sing_mass1_b6b808_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['mass2'], name='events_sing_mass2_f219c4_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['mchirp'], name='events_sing_mchirp_f15fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['mtotal'], name='events_sing_mtotal_414d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['snr'], name='events_sing_snr_357dba_idx'),
        ),
        migrations.AddIndex(
            model_name='singleinspiral',
            index=models.Index(fields=['chisq'], name='events_sing_chisq_85b169_idx'),
        ),
    ]
