# Generated by Django 3.2.9 on 2023-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_auto_20230126_2241'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='events_grou_name_4f9e1d_idx'),
        ),
    ]
