# Generated by Django 3.2.9 on 2023-01-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_group_events_grou_name_4f9e1d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created'], name='events_even_created_d68dd3_idx'),
        ),
    ]
