# Generated by Django 3.2.9 on 2023-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_new_emfollow_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlyburstevent',
            name='snr',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['snr'], name='events_mlyb_snr_464e20_idx'),
        ),
    ]
