# Generated by Django 3.2.9 on 2023-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_add_snr_optimized_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
