# Generated by Django 3.2.18 on 2023-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_missing_earlywarning_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiburstevent',
            name='code',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='multiburstevent',
            name='hoft',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='multiburstevent',
            name='mchirp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multiburstevent',
            name='strain',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['start_time'], name='events_mult_start_t_74b1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['peak_time'], name='events_mult_peak_ti_c1c776_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['mchirp'], name='events_mult_mchirp_b1db7c_idx'),
        ),
        migrations.AddIndex(
            model_name='multiburstevent',
            index=models.Index(fields=['code'], name='events_mult_code_fab3b0_idx'),
        ),
    ]
