# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:04
#
# Modified by hand on 2023-11-01.
#
from __future__ import unicode_literals

from django.db import migrations

# Creates initial search group instances

# List of search group names
SEARCH_GROUPS = [
    'Detchar',
]

def add_groups(apps, schema_editor):
    Group = apps.get_model('events', 'Group')

    # Create groups
    for group_name in SEARCH_GROUPS:
        group, created = Group.objects.get_or_create(name=group_name)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('events', 'Group')

    # Delete groups
    Group.objects.filter(name__in=SEARCH_GROUPS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0084_lensing_search_label'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups)
    ]
