# Generated by Django 4.2.10 on 2024-02-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_add_icecube_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeutrinoEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('ivorn', models.CharField(max_length=200, null=True)),
                ('coord_system', models.CharField(max_length=200, null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('error_radius', models.FloatField(null=True)),
                ('signalness', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('src_error_90', models.FloatField(null=True)),
                ('src_error_50', models.FloatField(null=True)),
                ('amon_id', models.BigIntegerField(null=True)),
                ('run_id', models.PositiveIntegerField(null=True)),
                ('event_id', models.PositiveIntegerField(null=True)),
                ('stream', models.PositiveIntegerField(null=True)),
                ('far_ne', models.FloatField(null=True)),
                ('far_unit', models.CharField(max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ivorn'], name='events_neut_ivorn_3ba7e5_idx'), models.Index(fields=['coord_system'], name='events_neut_coord_s_5392db_idx'), models.Index(fields=['ra'], name='events_neut_ra_5fd98d_idx'), models.Index(fields=['dec'], name='events_neut_dec_250378_idx'), models.Index(fields=['error_radius'], name='events_neut_error_r_b9e51f_idx'), models.Index(fields=['signalness'], name='events_neut_signaln_b90f17_idx'), models.Index(fields=['energy'], name='events_neut_energy_d11350_idx'), models.Index(fields=['src_error_90'], name='events_neut_src_err_27b466_idx'), models.Index(fields=['src_error_50'], name='events_neut_src_err_039571_idx'), models.Index(fields=['amon_id'], name='events_neut_amon_id_fbd455_idx'), models.Index(fields=['run_id'], name='events_neut_run_id_acd04a_idx'), models.Index(fields=['event_id'], name='events_neut_event_i_bb1d6a_idx'), models.Index(fields=['far_ne'], name='events_neut_far_ne_96b9e8_idx'), models.Index(fields=['stream'], name='events_neut_stream_37f8df_idx')],
            },
            bases=('events.event',),
        ),
    ]
