# Generated by Django 4.2.11 on 2024-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_add_gwak_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlyburstevent',
            name='background',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='bbh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='freq_correlation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='glitch',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='sghf',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='sglf',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['bbh'], name='events_mlyb_bbh_23f3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['sglf'], name='events_mlyb_sglf_44f9af_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['sghf'], name='events_mlyb_sghf_6ec60e_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['background'], name='events_mlyb_backgro_3aede4_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['glitch'], name='events_mlyb_glitch_29f11b_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['freq_correlation'], name='events_mlyb_freq_co_9b0644_idx'),
        ),
    ]
