# Generated by Django 4.2.11 on 2024-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_gwak_mlyburstevent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlyburstevent',
            name='channel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
