# Generated by Django 4.2.16 on 2024-09-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_mock_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labelling',
            unique_together={('event', 'label')},
        ),
    ]
