# Generated by Django 4.2.16 on 2024-10-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_alter_labelling_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlyburstevent',
            name='channel',
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='channels',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
