# Generated by Django 4.2.21 on 2025-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_create_blessed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlyburstevent',
            name='end_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='end_time_ns',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='mass1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='mass2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='mchirp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='mtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='spin1z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='spin2z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlyburstevent',
            name='template_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['mass1'], name='events_mlyb_mass1_56ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['mass2'], name='events_mlyb_mass2_06fba5_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['mchirp'], name='events_mlyb_mchirp_4ae17f_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['mtotal'], name='events_mlyb_mtotal_42df28_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['spin1z'], name='events_mlyb_spin1z_dbe148_idx'),
        ),
        migrations.AddIndex(
            model_name='mlyburstevent',
            index=models.Index(fields=['spin2z'], name='events_mlyb_spin2z_45308a_idx'),
        ),
    ]
