# Generated by Django 4.2.26 on 2026-02-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_add_perms_gin_index_and_populate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['gpstime', 'pipeline_id', 'far'], name='events_even_gpstime_586d07_idx'),
        ),
    ]
