#!/bin/sh

python3 /app/gracedb_project/manage.py update_user_accounts_from_ligo_ldap kagra
python3 /app/gracedb_project/manage.py update_user_accounts_from_ligo_ldap ligo
python3 /app/gracedb_project/manage.py remove_inactive_alerts
python3 /app/gracedb_project/manage.py clearsessions
python3 /app/gracedb_project/manage.py vacuum
python3 /app/gracedb_project/manage.py vacuum_full
