[program:apache2]
command=/usr/sbin/apache2ctl -DFOREGROUND
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
priority=2

[program:gracedb]
command=/usr/local/bin/gunicorn --reload --bind 0.0.0.0:8000 config.wsgi:application
directory=/app/gracedb_project
#user=www-data
#group=www-data
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
priority=1
