# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2018-12-05 02:41
from __future__ import unicode_literals

from django.db import migrations

GROUP_NAME = 'priority_users'

def create_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=GROUP_NAME)


def delete_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    g = Group.objects.get(name=GROUP_NAME)
    g.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0018_update_emfollow_groups'),
    ]

    operations = [
        migrations.RunPython(create_group, delete_group),
    ]
