# Generated by Django 2.0 on 2020-02-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0024_auto_20190919_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
