# Generated by Django 2.2 on 2020-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0025_auto_20200229_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='name'),
        ),
    ]
