# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_superevent'),
        ('superevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labelling',
            unique_together=set([('superevent', 'label')]),
        ),
    ]
