# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0002_superevent_label_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emobservation',
            name='N',
            field=models.IntegerField(editable=False),
        ),
    ]
