# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0003_emobservation_N_not_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superevent',
            name='base_date_number',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superevent',
            name='base_letter_suffix',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='gw_date_number',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='gw_letter_suffix',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='is_gw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superevent',
            name='t_0_date',
            field=models.DateField(default=datetime.date(2018, 5, 10), editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='superevent',
            unique_together=set([('t_0_date', 'gw_letter_suffix'), ('t_0_date', 'gw_date_number'), ('t_0_date', 'base_date_number'), ('t_0_date', 'base_letter_suffix')]),
        ),
    ]
