# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0004_add_fields_for_superevent_date_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superevent',
            name='preferred_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='superevent_preferred_for', to='events.Event'),
        ),
    ]
