# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 19:57
# Note from Tanner:
# This was auto-generated after moving to Python 3, with no changes to the
# actual models. See the commit message for more details.
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0004_populate_voevent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='instrument',
            field=models.CharField(blank=True, choices=[('H1', 'LHO'), ('L1', 'LLO'), ('V1', 'Virgo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='signoff_type',
            field=models.CharField(choices=[('OP', 'operator'), ('ADV', 'advocate')], max_length=3),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='status',
            field=models.CharField(choices=[('OK', 'OKAY'), ('NO', 'NOT OKAY')], max_length=2),
        ),
        migrations.AlterField(
            model_name='superevent',
            name='category',
            field=models.CharField(choices=[('P', 'Production'), ('T', 'Test'), ('M', 'MDC')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='ivorn',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='voevent_type',
            field=models.CharField(choices=[('PR', 'preliminary'), ('IN', 'initial'), ('UP', 'update'), ('RE', 'retraction')], max_length=2),
        ),
    ]
