# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0005_preferred_event_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superevent',
            name='alert_sent',
        ),
    ]
