# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 18:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0005_auto_20190919_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='Superevent',
            name='coinc_far',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Superevent',
            name='em_type',
            field=models.CharField(null=True, blank=True, max_length=100),
        ),
    ]
