# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 18:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0006_add_coinc_far_and_em_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voevent',
            name='raven_coinc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voevent',
            name='combined_skymap_filename',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='ext_gcn',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='ext_pipeline',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='ext_search',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='time_coinc_far',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='space_coinc_far',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='voevent',
            name='delta_t',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
