# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-29 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0006_remove_superevent_alert_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superevent',
            options={'ordering': ['-id'], 'permissions': (('view_superevent', 'Can view superevent'), ('confirm_gw_superevent', 'Can confirm as a superevent as a GW'))},
        ),
    ]
