# Generated by Django 2.2 on 2020-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0006_add_raven_voevent_sevent_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['-created', '-N'], 'permissions': (('expose_log', 'Can expose a log to be viewed by external users'), ('hide_log', 'Can hide a log from external users'), ('tag_log', 'Add tag to log'), ('untag_log', 'Remove tag from log'), ('view_log', 'Can view log'))},
        ),
        migrations.AlterModelOptions(
            name='signoff',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_signoff', 'Can view signoff'), ('do_H1_signoff', 'Can interact with H1 signoffs'), ('do_L1_signoff', 'Can interact with L1 signoffs'), ('do_V1_signoff', 'Can interact with V1 signoffs'), ('do_adv_signoff', 'Can interact with advocate signoffs'))},
        ),
        migrations.AlterModelOptions(
            name='superevent',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['-id'], 'permissions': (('add_test_superevent', 'Can add test superevent'), ('add_mdc_superevent', 'Can add MDC superevent'), ('change_test_superevent', 'Can change test superevent'), ('change_mdc_superevent', 'Can change MDC superevent'), ('confirm_gw_superevent', 'Can confirm superevent as GW'), ('confirm_gw_test_superevent', 'Can confirm test superevent as GW'), ('confirm_gw_mdc_superevent', 'Can confirm MDC superevent as GW'), ('annotate_superevent', 'Can add log messages and EM observation data to superevent'), ('expose_superevent', 'Can expose a superevent to be viewed by external users'), ('hide_superevent', 'Can hide a superevent from external users'), ('view_superevent', 'Can view superevent'))},
        ),
        migrations.AlterModelOptions(
            name='supereventgroupobjectpermission',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_supereventgroupobjectpermission', 'Can view superevent groupobjectpermission'),)},
        ),
        migrations.AlterField(
            model_name='voevent',
            name='coinc_comment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='hardware_inj',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='internal',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='open_alert',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voevent',
            name='raven_coinc',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
