# Generated by Django 2.2.10 on 2020-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0007_auto_20200303_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voevent',
            name='voevent_type',
            field=models.CharField(choices=[('PR', 'preliminary'), ('IN', 'initial'), ('UP', 'update'), ('RE', 'retraction'), ('EW', 'earlywarning')], max_length=2),
        ),
    ]
