# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-09 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0007_add_gw_permission_to_superevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superevent',
            old_name='date_created',
            new_name='created',
        ),
    ]
