# Generated by Django 2.2.10 on 2020-03-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0008_auto_20200313_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superevent',
            old_name='coinc_far',
            new_name='time_coinc_far',
        ),
    ]
