# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0009_emobservation_fields_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='category',
            field=models.CharField(choices=[(b'P', b'Production'), (b'T', b'Test'), (b'M', b'MDC')], default=b'P', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='superevent',
            unique_together=set([('t_0_date', 'gw_letter_suffix', 'category'), ('t_0_date', 'base_date_number', 'category'), ('t_0_date', 'gw_date_number', 'category'), ('t_0_date', 'base_letter_suffix', 'category')]),
        ),
    ]
