# Generated by Django 2.2.10 on 2020-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0009_rename_coinc_far'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='space_coinc_far',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
