# Generated by Django 3.2.9 on 2022-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0010_superevent_space_coinc_far'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='default_superevent_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='gw_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='superevent_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
