# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0010_superevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superevent',
            name='base_letter_suffix',
            field=models.CharField(default='a', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
