# Generated by Django 2.2.10 on 2020-08-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0010_superevent_space_coinc_far'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='gw_id',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
