# Generated by Django 2.2.10 on 2020-08-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0011_superevent_gw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='superevent',
            name='default_superevent_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='superevent',
            name='superevent_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
