# Generated by Django 3.2.9 on 2023-01-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0012_voevent_prob_has_mass_gap'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['superevent_id'], name='superevents_superev_f49162_idx'),
        ),
    ]
