# Generated by Django 3.2.9 on 2023-01-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0013_superevent_superevents_superev_f49162_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['filename'], name='superevents_filenam_3e563f_idx'),
        ),
    ]
