# Generated by Django 3.2.9 on 2023-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0014_log_superevents_filenam_3e563f_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['gw_id'], name='superevents_gw_id_5ef90d_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['t_0'], name='superevents_t_0_d2d6db_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['t_start'], name='superevents_t_start_801e07_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['t_end'], name='superevents_t_end_6afecc_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['created'], name='superevents_created_9703fb_idx'),
        ),
    ]
