# Generated by Django 3.2.9 on 2023-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0015_auto_20230126_1837'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['default_superevent_id'], name='superevents_default_0095cf_idx'),
        ),
    ]
