# Generated by Django 3.2.9 on 2023-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0016_superevent_superevents_default_0095cf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='voevent',
            name='significant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
