# Generated by Django 3.2.9 on 2023-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0017_voevent_significant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['category'], name='superevents_categor_822b70_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['base_date_number'], name='superevents_base_da_f3f2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='superevent',
            index=models.Index(fields=['base_letter_suffix'], name='superevents_base_le_fb8854_idx'),
        ),
    ]
