# Generated by Django 4.2.11 on 2024-05-30 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superevents', '0019_alter_emobservation_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voevent',
            name='prob_has_ssm',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
