# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 16:05
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
import socket

SITES = {
    'old': {
        'domain': 'example.com',
        'name': 'example.com',
    },
    'new': {
        'domain': socket.gethostname() + '.ligo.org',
        'name': 'ligo.org',
    },
}

def update_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    # Get current site matching SITE_ID, should be example.com at this point
    site1 = Site.objects.get(id=settings.SITE_ID)

    # Update with new site name and domain
    site1.name = SITES['new']['name']
    site1.domain = SITES['new']['domain']
    site1.save()


def revert_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    # Get current site matching SITE_ID should be ligo.org
    site1 = Site.objects.get(id=settings.SITE_ID)

    # Revert to original site
    site1.name = SITES['old']['name']
    site1.domain = SITES['old']['domain']
    site1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site, revert_site),
    ]
