# Generated by Django 3.2.9 on 2021-11-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_update_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
