# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_separate_call_and_text_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='contacts',
            field=models.ManyToManyField(to='userprofile.Contact'),
        ),
    ]
