# Generated by Django 2.2 on 2020-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0010_authorize_raven_users_to_populate_new_pipelines'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='guardian_us_content_179ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='guardian_gr_content_ae6aec_idx'),
        ),
    ]
