# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0011_update_virgo_detchar_cert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalUser',
            new_name='RobotUser',
        ),
    ]
