# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0012_rename_localuser_to_robotuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='x509cert',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
