# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 19:50
from __future__ import unicode_literals

from django.db import migrations

ACCOUNT = {
    'username': 'Gwhen',
    'email': 'stefan.countryman@ligo.org',
    'first_name': '',
    'last_name': 'GWHEN',
}

CERTS = [
    '/DC=org/DC=cilogon/C=US/O=LIGO/OU=Robots/CN=gwhen.com/CN=gwhen/CN=Stefan Countryman/CN=UID:stefan.countryman.robot',
]


def create_account_and_certs(apps, schema_editor):
    RobotUser = apps.get_model('ligoauth', 'RobotUser')
    X509Cert = apps.get_model('ligoauth', 'X509Cert')

    # Create user
    user = RobotUser.objects.create(**ACCOUNT)

    # Create X509 certificates
    for subject in CERTS:
        user.x509cert_set.create(subject=subject)


def delete_account_and_certs(apps, schema_editor):
    RobotUser = apps.get_model('ligoauth', 'RobotUser')
    X509Cert = apps.get_model('ligoauth', 'X509Cert')

    # Get user
    user = RobotUser.objects.get(username=ACCOUNT['username'])

    # Delete certs
    for cert in user.x509cert_set.filter(subject__in=CERTS):
        cert.delete()

    # Delete full User object
    user.user_ptr.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0023_update_geo_cert'),
    ]

    operations = [
        migrations.RunPython(create_account_and_certs,
            delete_account_and_certs),
    ]
