# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0038_populate_authgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateemail',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlternateEmail',
        ),
    ]
