# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0039_delete_alternateemail_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='x509cert',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
