# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ligoauth', '0040_x509cert_unique_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='x509cert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='x509cert',
            name='users',
            field=models.ManyToManyField(related_name='certs', to=settings.AUTH_USER_MODEL),
        ),
    ]
