# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0042_populate_x509cert_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='x509cert',
            name='users',
        ),
        migrations.AlterField(
            model_name='x509cert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
