# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_add_subgrb_search'),
        ('superevents', '0002_fix_permission_typo'),
        ('alerts', '0003_add_created_updated_time_fields_to_notification'),
        ('django_twilio', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('guardian', '0005_authorize_raven_users_to_populate_pipelines'),
        ('user_sessions', '0003_auto_20161205_1516'),
        ('ligoauth', '0045_populate_robot_accounts_authgroup'),
    ]

    # NOTE: I (TP) commented out the RemoveField operation since it was giving
    # an error like (1090, "You can't delete all columns with ALTER TABLE; use
    # DROP TABLE instead").  There are a few issues about this:
    #     https://code.djangoproject.com/ticket/27746
    #     https://code.djangoproject.com/ticket/24424
    # It looks like it may be fixed in Django 2.2.2, so we can test it out once
    # we get to that version.
    operations = [
        #migrations.RemoveField(
        #    model_name='robotuser',
        #    name='user_ptr',
        #),
        migrations.DeleteModel(
            name='RobotUser',
        ),
    ]
