# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0060_add_emfollow-test_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedLdapMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_gname', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('ldap_authgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligoauth.AuthGroup')),
            ],
        ),
    ]
