# Generated by Django 2.2.10 on 2020-12-03 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ligoauth', '0069_setup_asimov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedldapmember',
            name='ldap_gname',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GenericLdapUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(max_length=255, unique=True)),
                ('ldap_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligoauth.AuthorizedLdapMember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='x509cert',
            name='ldap_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligoauth.GenericLdapUser'),
        ),
    ]
