# Generated by Django 3.2.9 on 2023-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoauth', '0083_another_spiir_cert'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='x509cert',
            index=models.Index(fields=['subject'], name='ligoauth_x5_subject_15a923_idx'),
        ),
    ]
